import { describe,expect,it } from 'vitest'
import { canPlace,canPlaceAny,centeredOrigin,completedLines,emptyBoard,isBoardEmpty,multiplierAt,place,resolve,scoreResolution } from './engine'
import type { Board, Piece } from './types'
const one:Piece={id:'p',cells:[{row:0,col:0,letter:'A'}]}
const piece=(letters:string,vertical=false):Piece=>({id:letters,cells:[...letters].map((letter,i)=>({row:vertical?i:0,col:vertical?0:i,letter}))})
describe('placement',()=>{it('accepts a valid figure',()=>expect(canPlace(emptyBoard(),one,{row:0,col:0})).toBe(true));it('rejects outside board',()=>expect(canPlace(emptyBoard(),piece('AAA'),{row:7,col:7})).toBe(false));it('rejects overlaps',()=>{const b=place(emptyBoard(),one,{row:2,col:2});expect(canPlace(b,one,{row:2,col:2})).toBe(false)})})
describe('drag preview',()=>{it('centers an odd-width piece under the pointer',()=>expect(centeredOrigin({row:2,col:4},piece('ABC'))).toEqual({row:2,col:3}));it('centers an even-width piece between cells',()=>expect(centeredOrigin({row:2,col:3.5},piece('AB'))).toEqual({row:2,col:3}));it('centers a vertical piece under the lifted pointer',()=>expect(centeredOrigin({row:4,col:2},piece('ABC',true))).toEqual({row:3,col:2}))})
describe('board clearing',()=>{it('recognizes an empty board',()=>expect(isBoardEmpty(emptyBoard())).toBe(true));it('does not recognize an occupied board as empty',()=>expect(isBoardEmpty(place(emptyBoard(),one,{row:0,col:0}))).toBe(false));it('recognizes a board emptied by a word',()=>expect(isBoardEmpty(resolve(place(emptyBoard(),piece('DIA'),{row:0,col:0})).board)).toBe(true))})
describe('lines',()=>{it('finds a full row',()=>{let b=emptyBoard();for(let c=0;c<8;c++)b=place(b,{...one,id:String(c)},{row:0,col:c});expect(completedLines(b)).toHaveLength(1)});it('finds a full column',()=>{let b=emptyBoard();for(let r=0;r<8;r++)b=place(b,{...one,id:String(r)},{row:r,col:0});expect(completedLines(b)).toHaveLength(1)});it('finds several lines',()=>{const b=Array.from({length:8},()=>Array.from({length:8},()=>({letter:'A',id:'x'}))) as Board;expect(completedLines(b)).toHaveLength(16)})})
describe('words and scoring',()=>{it('detects horizontal words',()=>{const b=place(emptyBoard(),piece('CASA'),{row:1,col:1});expect(resolve(b).words[0].word).toBe('CASA')});it('detects a word inside a longer sequence',()=>{const b=place(emptyBoard(),piece('AXDIAU'),{row:1,col:1}),r=resolve(b);expect(r.words.map(w=>w.word)).toContain('DIA');expect(r.baseScore).toBe(30);expect(r.removed.map(p=>p.col)).toEqual([3,4,5]);expect(r.board[1][1]?.letter).toBe('A');expect(r.board[1][6]?.letter).toBe('U')});it('detects vertical words',()=>{const b=place(emptyBoard(),piece('SOL',true),{row:1,col:1});expect(resolve(b).words[0].word).toBe('SOL')});it('scores words',()=>{const r=resolve(place(emptyBoard(),piece('CASA'),{row:0,col:0}));expect(scoreResolution(r,3)).toBe(120)});it('scores lines',()=>{const b=Array.from({length:8},(_,r)=>Array.from({length:8},(_,c)=>r===0?{letter:'X',id:String(c)}:null)) as Board;expect(scoreResolution(resolve(b),4)).toBe(80)});it('scores simultaneous word and line',()=>{const b=emptyBoard();for(let c=0;c<8;c++)b[0][c]={letter:'X',id:String(c)};['C','A','S','A'].forEach((letter,r)=>b[r][0]={letter,id:`w${r}`});const r=resolve(b);expect(r.lines).toHaveLength(1);expect(r.words[0].word).toBe('CASA');expect(scoreResolution(r,4)).toBe(240);expect(r.removed.filter(p=>p.row===0&&p.col===0)).toHaveLength(1)})})
describe('multiplier',()=>{it('steps from 5 to 1',()=>expect([0,3000,6000,9000,12000,50000].map(multiplierAt)).toEqual([5,4,3,2,1,1]));it('can restart after score',()=>{let started=0;expect(multiplierAt(9000-started)).toBe(2);started=9000;expect(multiplierAt(9000-started)).toBe(5)})})
it('detects game over',()=>{const b=Array.from({length:8},()=>Array.from({length:8},()=>({letter:'X',id:'x'}))) as Board;expect(canPlaceAny(b,[one])).toBe(false)})
