import { useCallback,useEffect,useRef,useState } from 'react'
import { canPlace,canPlaceAny,centeredOrigin,emptyBoard,isBoardEmpty,key,multiplierAt,place,resolve,scoreResolution,SIZE } from '../game/engine'
import { makeTray } from '../game/pieces'
import type { Board,Piece,Point } from '../game/types'
type Drag={piece:Piece;index:number;origin:Point|null;x:number;y:number}
type GameMode='classic'|'level'
type ClassicSave={board:Board;pieces:Piece[];score:number;cycle:number;recentWords:string[];palette:number;pausedAt:number}
const VERSION='v0.5.1'
const RESOLUTION_MS=1100
const INITIAL_TIME=Date.now()
const storage=(name:string)=>`letter-fusion-${name}`
const legacyStorage=(name:string)=>`letter-blast-${name}`
const readStored=(name:string)=>localStorage.getItem(storage(name))??localStorage.getItem(legacyStorage(name))
const readCompletedLevels=()=>{try{return new Set<number>(JSON.parse(readStored('completed-levels')||'[]'))}catch{return new Set<number>()}}
export default function App(){
 const [screen,setScreen]=useState<'menu'|'levels'|'shop'|'game'>('menu');const [gameMode,setGameMode]=useState<GameMode>('classic');const [menuNotice,setMenuNotice]=useState('');const [shopNotice,setShopNotice]=useState('');const [board,setBoard]=useState<Board>(emptyBoard);const [pieces,setPieces]=useState<Piece[]>(makeTray);const [score,setScore]=useState(0);const [cycle,setCycle]=useState(INITIAL_TIME);const [now,setNow]=useState(INITIAL_TIME);const [drag,setDrag]=useState<Drag|null>(null);const [toast,setToast]=useState<string[]>([]);const [recentWords,setRecentWords]=useState<string[]>([]);const [palette,setPalette]=useState(0);const [removing,setRemoving]=useState(new Set<string>());const [currentLevel,setCurrentLevel]=useState(1);const [levelWords,setLevelWords]=useState(0);const [levelComplete,setLevelComplete]=useState(false);const [unlockedLevel,setUnlockedLevel]=useState(()=>Math.min(100,Math.max(1,Number(readStored('unlocked-level'))||1)));const [completedLevels,setCompletedLevels]=useState(readCompletedLevels);const [gems,setGems]=useState(()=>Math.max(0,Number(readStored('gems'))||0));const boardRef=useRef<HTMLDivElement>(null);const classicSave=useRef<ClassicSave|null>(null);const multiplier=multiplierAt(now-cycle);const gameOver=!canPlaceAny(board,pieces);const dragging=drag!==null
 useEffect(()=>{const id=setInterval(()=>setNow(Date.now()),200);return()=>clearInterval(id)},[])
 useEffect(()=>{document.body.classList.toggle('drag-active',dragging);return()=>document.body.classList.remove('drag-active')},[dragging])
 const locate=useCallback((x:number,y:number,piece:Piece)=>{const board=boardRef.current,first=board?.children[0]?.getBoundingClientRect(),right=board?.children[1]?.getBoundingClientRect(),below=board?.children[SIZE]?.getBoundingClientRect();if(!first||!right||!below)return null;const col=(x-(first.left+first.width/2))/(right.left-first.left),row=(y-(first.top+first.height/2))/(below.top-first.top);return centeredOrigin({row,col},piece)},[])
 const start=(e:React.PointerEvent,index:number)=>{e.preventDefault();e.currentTarget.setPointerCapture(e.pointerId);const p=pieces[index];setDrag({piece:p,index,origin:locate(e.clientX,e.clientY-70,p),x:e.clientX,y:e.clientY})}
 const move=(e:React.PointerEvent)=>{e.preventDefault();setDrag(d=>d?{...d,x:e.clientX,y:e.clientY,origin:locate(e.clientX,e.clientY-70,d.piece)}:null)}
 const finish=()=>{
  if(!drag)return
  const {piece,index,origin}=drag;setDrag(null)
  if(!origin||!canPlace(board,piece,origin))return
  const placed=place(board,piece,origin),result=resolve(placed),m=multiplier
  const nextPieces=pieces.filter((_,i)=>i!==index)
  if(result.baseScore){
   const cleared=isBoardEmpty(result.board)
   const earned=scoreResolution(result,m),nextScore=score+earned,nextWords=levelWords+result.words.length
   setScore(nextScore);setLevelWords(nextWords);setCycle(Date.now());setNow(Date.now())
   setToast([`×${m}`])
   if(cleared)setPalette(color=>(color+1)%5)
   if(result.words.length)setRecentWords(words=>[...result.words.map(w=>w.word),...words].slice(0,6))
   setRemoving(new Set(result.removed.map(key)));setBoard(placed)
   setTimeout(()=>{setBoard(result.board);setRemoving(new Set());setToast([]);if(gameMode==='level'&&(nextWords>=currentLevel||nextScore>=currentLevel*250)){const nextUnlocked=Math.min(100,Math.max(unlockedLevel,currentLevel+1)),nextCompleted=new Set(completedLevels).add(currentLevel);setUnlockedLevel(nextUnlocked);setCompletedLevels(nextCompleted);localStorage.setItem(storage('unlocked-level'),String(nextUnlocked));localStorage.setItem(storage('completed-levels'),JSON.stringify([...nextCompleted]));setLevelComplete(true)}},RESOLUTION_MS)
  }else setBoard(placed)
  setPieces(nextPieces.length?nextPieces:makeTray())
 }
 const reset=()=>{setBoard(emptyBoard());setPieces(makeTray());setScore(0);setLevelWords(0);setLevelComplete(false);setCycle(Date.now());setNow(Date.now());setToast([]);setRecentWords([]);setPalette(0);setRemoving(new Set())}
 const openMenu=()=>{if(gameMode==='classic')classicSave.current={board,pieces,score,cycle,recentWords,palette,pausedAt:Date.now()};setDrag(null);setScreen('menu')}
 const startClassic=()=>{const resumedAt=Date.now(),saved=classicSave.current;setGameMode('classic');if(saved){setBoard(saved.board);setPieces(saved.pieces);setScore(saved.score);setCycle(saved.cycle+(resumedAt-saved.pausedAt));setRecentWords(saved.recentWords);setPalette(saved.palette);setNow(resumedAt);setLevelComplete(false)}else reset();setMenuNotice('');setScreen('game')}
 const startLevel=(level:number)=>{setCurrentLevel(level);setGameMode('level');reset();setScreen('game')}
 const retryLevel=()=>{if(gems<1){setScreen('shop');return}const next=gems-1;setGems(next);localStorage.setItem(storage('gems'),String(next));reset()}
 if(screen==='menu')return <StartMenu notice={menuNotice} onLevels={()=>setScreen('levels')} onClassic={startClassic} onShop={()=>setScreen('shop')} onUnavailable={mode=>setMenuNotice(`${mode} · PRÓXIMAMENTE`)}/>
 if(screen==='levels')return <LevelSelect unlocked={unlockedLevel} completed={completedLevels} gems={gems} onBack={()=>setScreen('menu')} onSelect={startLevel}/>
 if(screen==='shop')return <Shop gems={gems} notice={shopNotice} onBack={()=>setScreen('menu')} onBuy={()=>setShopNotice('PAGO SEGURO PENDIENTE DE CONECTAR')}/>
 const preview=new Set<string>();if(drag?.origin)drag.piece.cells.forEach(c=>preview.add(key({row:drag.origin!.row+c.row,col:drag.origin!.col+c.col})));const valid=!!(drag?.origin&&canPlace(board,drag.piece,drag.origin))
 return <main className={`${removing.size?'resolving ':''}palette-${palette}`}>
  <header><div><span className="eyebrow">WORD PUZZLE</span><h1>LETTER <b>FUSION</b></h1></div><div className="header-actions"><button onClick={openMenu}>MENÚ</button>{gameMode==='level'&&<b className="gem-count">💎 {gems}</b>}<VersionButton/></div></header>
  {gameMode==='level'&&<section className="level-progress"><b>NIVEL {currentLevel}</b><span>{levelWords}/{currentLevel} PALABRAS</span><span>{score}/{currentLevel*250} PUNTOS</span></section>}
  <section className="hud"><div><small>PUNTOS</small><strong>{String(score).padStart(4,'0')}</strong></div><div className="mult"><small>MULTIPLICADOR</small><strong>×{multiplier}</strong><i style={{transform:`scaleX(${multiplier===1?0:Math.max(0,1-(now-cycle)%3000/3000)})`}}/></div></section>
  <section className="word-history" aria-live="polite"><small>ÚLTIMAS PALABRAS</small><div>{recentWords.length?recentWords.map((word,i)=><span key={`${word}-${i}`}>{word}</span>):<em>—</em>}</div></section>
  <div className="stage"><div className="board" ref={boardRef}>{board.flatMap((row,r)=>row.map((cell,c)=><div key={`${r}-${c}`} className={`cell ${cell?'filled':''} ${preview.has(`${r}:${c}`)?(valid?'preview valid':'preview invalid'):''} ${removing.has(`${r}:${c}`)?'removing':''}`}>{cell?.letter}</div>))}</div>{toast.length>0&&<div className="toasts" aria-live="assertive">{toast.map((t,i)=><span key={i}>{t}</span>)}</div>}</div>
  <div className="tray">{pieces.map((p,i)=><div className={`piece-slot ${drag?.index===i?'dragging':''}`} key={p.id} onPointerDown={e=>start(e,i)} onPointerMove={move} onPointerUp={finish} onPointerCancel={()=>setDrag(null)} onDragStart={e=>e.preventDefault()}><PieceView piece={p}/></div>)}</div><p className="hint">ARRASTRA UNA FIGURA AL TABLERO</p>
  {drag&&<div className="drag-ghost" style={{left:drag.x,top:drag.y-70}}><PieceView piece={drag.piece}/></div>}{levelComplete&&<div className="modal level-won"><div><span>OBJETIVO CONSEGUIDO</span><h2>NIVEL {currentLevel}</h2><p>{levelWords} PALABRAS · {score} PUNTOS</p>{currentLevel<100&&<button onClick={()=>startLevel(currentLevel+1)}>SIGUIENTE NIVEL</button>}<button className="secondary" onClick={()=>setScreen('levels')}>VER NIVELES</button></div></div>}{gameOver&&!levelComplete&&<div className="modal"><div><span>FIN DE LA PARTIDA</span><h2>GAME OVER</h2><p>PUNTUACIÓN FINAL</p><strong>{score}</strong>{gameMode==='level'?<><button onClick={retryLevel}>{gems?'REPETIR · 1 💎':'CONSEGUIR GEMAS'}</button><small className="gem-balance">TIENES {gems} 💎</small></>:<button onClick={reset}>NUEVA PARTIDA</button>}</div></div>}<footer>Forma palabras · Completa líneas · Mantén el ×5</footer>
 </main>
}
function StartMenu({notice,onLevels,onClassic,onShop,onUnavailable}:{notice:string;onLevels:()=>void;onClassic:()=>void;onShop:()=>void;onUnavailable:(mode:string)=>void}){return <main className="start-menu"><div className="menu-glow"/><section className="menu-content"><div className="menu-logo" aria-label="Letter Fusion"><div className="menu-logo-mark"><i>L</i><i>F</i><i/><i/></div><span>JUEGO DE PALABRAS</span><h1>LETTER <b>FUSION</b></h1><p className="menu-tagline">Fusiona letras, forma palabras y supera 100 niveles.</p></div><nav className="mode-buttons" aria-label="Modos de juego"><button className="levels" onClick={onLevels}><small>AVENTURA</small>NIVELES</button><button className="classic" onClick={onClassic}><small>JUEGO ORIGINAL</small>CLASSIC</button><button className="club" onClick={()=>onUnavailable('CLUB')}><small>COMUNIDAD</small>CLUB</button><button className="shop" onClick={onShop}><small>MEJORAS Y EXTRAS</small>TIENDA</button></nav><p className="menu-notice" aria-live="polite">{notice||'ELIGE TU MODO DE JUEGO'}</p><VersionButton menu/></section></main>}
function LevelSelect({unlocked,completed,gems,onBack,onSelect}:{unlocked:number;completed:Set<number>;gems:number;onBack:()=>void;onSelect:(level:number)=>void}){return <main className="level-select"><header><button onClick={onBack}>‹ MENÚ</button><div><span className="eyebrow">AVENTURA</span><h1>100 <b>NIVELES</b></h1></div><b className="gem-count">💎 {gems}</b></header><p className="level-rule">Supera cada nivel formando palabras <b>o</b> alcanzando los puntos indicados.</p><div className="level-grid">{Array.from({length:100},(_,i)=>i+1).map(level=>{const locked=level>unlocked,done=completed.has(level);return <div className="level-stop" key={level}><button className={done?'completed':''} disabled={locked} onClick={()=>onSelect(level)}><i className="door-chain"/><i className="door-lock"/><strong>{locked?'':done?'✓':level}</strong><small>NIVEL {level}</small><small>{done?'COMPLETADO':`${level} ${level===1?'PALABRA':'PALABRAS'} · ${level*250} PTOS.`}</small></button></div>})}</div></main>}
function Shop({gems,notice,onBack,onBuy}:{gems:number;notice:string;onBack:()=>void;onBuy:()=>void}){return <main className="shop-screen"><header><button onClick={onBack}>‹ MENÚ</button><div><span className="eyebrow">LETTER FUSION</span><h1>TIENDA <b>💎</b></h1></div><VersionButton/></header><section className="wallet"><small>TU MONEDERO</small><strong>💎 {gems}</strong></section><h2>GEMAS</h2><p>Cada gema vale 1 € y permite repetir un nivel perdido.</p><div className="gem-packs">{[1,5,10].map(amount=><button key={amount} onClick={onBuy}><span>💎</span><strong>{amount} {amount===1?'GEMA':'GEMAS'}</strong><b>{amount} €</b><small>1 € POR GEMA</small></button>)}</div><p className="shop-notice" aria-live="polite">{notice||'LAS COMPRAS REALES REQUIEREN UNA PASARELA DE PAGO SEGURA'}</p></main>}
function VersionButton({menu=false}:{menu?:boolean}){const [updating,setUpdating]=useState(false);const update=async()=>{if(updating)return;setUpdating(true);try{if(!('serviceWorker' in navigator)){location.reload();return}const registration=await navigator.serviceWorker.getRegistration()??await navigator.serviceWorker.register('/sw.js');await registration.update();if(registration.waiting){navigator.serviceWorker.addEventListener('controllerchange',()=>location.reload(),{once:true});registration.waiting.postMessage({type:'SKIP_WAITING'});setTimeout(()=>location.reload(),1500)}else location.reload()}catch{location.reload()}};return <button type="button" className={menu?'menu-version version-update':'version version-update'} onClick={update} title="Buscar actualización" aria-label={`Versión ${VERSION}. Pulsar para actualizar`}>{updating?'ACTUALIZANDO…':VERSION}</button>}
function PieceView({piece}:{piece:Piece}){const rows=Math.max(...piece.cells.map(c=>c.row))+1,cols=Math.max(...piece.cells.map(c=>c.col))+1;return <div className="piece" style={{gridTemplateColumns:`repeat(${cols},var(--piece-cell))`,gridTemplateRows:`repeat(${rows},var(--piece-cell))`}}>{piece.cells.map((c,i)=><div className="mini" key={i} style={{gridRow:c.row+1,gridColumn:c.col+1}}>{c.letter}</div>)}</div>}
